{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.craftbenchmc",
    "module": "craftbench-api",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "craftbench-api-0.1.0.jar",
          "url": "craftbench-api-0.1.0.jar",
          "size": 261,
          "sha512": "8ae3fb11c76ae96560bcef663633d0cdff68b19e47f9d8d338918f1bccb3d7b5d1846329f77807a08ed37c5191be2acb0a5197faa37de66894050af3e222cc6f",
          "sha256": "840788395770034e4178f12dce64f259b3a4600bef521a56e586b18f78565c02",
          "sha1": "9289c6c0e7df25999ea1b47bee8719a479831491",
          "md5": "16e936c3b9405f78d50f373db137ebc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "craftbench-api-0.1.0.jar",
          "url": "craftbench-api-0.1.0.jar",
          "size": 261,
          "sha512": "8ae3fb11c76ae96560bcef663633d0cdff68b19e47f9d8d338918f1bccb3d7b5d1846329f77807a08ed37c5191be2acb0a5197faa37de66894050af3e222cc6f",
          "sha256": "840788395770034e4178f12dce64f259b3a4600bef521a56e586b18f78565c02",
          "sha1": "9289c6c0e7df25999ea1b47bee8719a479831491",
          "md5": "16e936c3b9405f78d50f373db137ebc7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "craftbench-api-0.1.0-javadoc.jar",
          "url": "craftbench-api-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "a7fd39b768e4b81cc4257665d3b6391062473378209398bafca2a0787ee6c7d12c17dd4051766916aa47d17d69ed4d5dfccd63a19e90653eacb3eb9b31696c48",
          "sha256": "f67e9ddd40d5b7ecb8559c10c102117e4cc69fc3c6084ee82831f18aa69decc5",
          "sha1": "282e8309b95ad92c0256241f275673d967f21cda",
          "md5": "e3570f1a2b419d39d3f5b10add9f4082"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "craftbench-api-0.1.0-sources.jar",
          "url": "craftbench-api-0.1.0-sources.jar",
          "size": 261,
          "sha512": "a7fd39b768e4b81cc4257665d3b6391062473378209398bafca2a0787ee6c7d12c17dd4051766916aa47d17d69ed4d5dfccd63a19e90653eacb3eb9b31696c48",
          "sha256": "f67e9ddd40d5b7ecb8559c10c102117e4cc69fc3c6084ee82831f18aa69decc5",
          "sha1": "282e8309b95ad92c0256241f275673d967f21cda",
          "md5": "e3570f1a2b419d39d3f5b10add9f4082"
        }
      ]
    }
  ]
}
