{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.craftbenchmc",
    "module": "craftbench",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "craftbench-0.1.0.jar",
          "url": "craftbench-0.1.0.jar",
          "size": 261,
          "sha512": "df201b1cdf017ea7d558da42a0c5a1ca71f0c9b1e3dd3d47d6973b1b3502a625dd404ffdb9d0b67b5760259d0c658c9c14c23c4c4f9344f1f910555f91412214",
          "sha256": "0820a2ae99542d8ff1974d2d3ff5faf424fc9dbb3a043cd51dc97c51afd46685",
          "sha1": "f35a9f8f4619e9ad8885666e602b4ff15e36957f",
          "md5": "47e707afadb59681a60dae53f14699c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "craftbench-0.1.0.jar",
          "url": "craftbench-0.1.0.jar",
          "size": 261,
          "sha512": "df201b1cdf017ea7d558da42a0c5a1ca71f0c9b1e3dd3d47d6973b1b3502a625dd404ffdb9d0b67b5760259d0c658c9c14c23c4c4f9344f1f910555f91412214",
          "sha256": "0820a2ae99542d8ff1974d2d3ff5faf424fc9dbb3a043cd51dc97c51afd46685",
          "sha1": "f35a9f8f4619e9ad8885666e602b4ff15e36957f",
          "md5": "47e707afadb59681a60dae53f14699c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "craftbench-0.1.0-javadoc.jar",
          "url": "craftbench-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "2d3267d38e982c18b3387cc34be56acfbffea8aad57beb779bfdee8a39dc6898b9004745674da7d35f8516f31ad68dfdd691d7f87c5f8adea5023df681dacb1c",
          "sha256": "a23556e589f246deb102b4d8b3b24d356e2c7bbc692dd2b1fa3b877d852838c2",
          "sha1": "257f1e279bbc1ff279a59de5aaffd1330a721bb0",
          "md5": "c3e11a5a0066829516e04c5502b7d2c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "craftbench-0.1.0-sources.jar",
          "url": "craftbench-0.1.0-sources.jar",
          "size": 261,
          "sha512": "a7fd39b768e4b81cc4257665d3b6391062473378209398bafca2a0787ee6c7d12c17dd4051766916aa47d17d69ed4d5dfccd63a19e90653eacb3eb9b31696c48",
          "sha256": "f67e9ddd40d5b7ecb8559c10c102117e4cc69fc3c6084ee82831f18aa69decc5",
          "sha1": "282e8309b95ad92c0256241f275673d967f21cda",
          "md5": "e3570f1a2b419d39d3f5b10add9f4082"
        }
      ]
    }
  ]
}
